services:
  - type: static
    name: pmsimplex-frontend
    env: static
    buildCommand: pnpm install && pnpm run build
    publishPath: dist
    branch: main
    envVars:
      - key: VITE_API_URL
        value: https://pmsimplex-b-04-04-26.onrender.com
    headers:
      - path: /assets/*.css
        name: Content-Type
        value: text/css
      - path: /assets/*.js
        name: Content-Type
        value: application/javascript
    routes:
      - type: rewrite
        source: /*
        destination: /index.html